# ~/aica/tmuxinator/aica-config.yml

name: aica-config
root: ~/aica

#pre_window: export currenttp=1

windows:
  - config-workspace:
      layout: tiled
      panes:
        - export currentuser=O && sudo cd /home/robot$currentuser/aica
# Duplicate above line for each container you need for your practical lessons. Increment currentuser=0