#syntax=ghcr.io/aica-technology/app-builder:v2

[core]
"image" = "v5.1.0"

[packages]
# add components
#"@aica/components/rl-policy-components" = "v3.0.0"
"@aica/components/advanced-perception" = "v1.0.0" # contains YoloExecutor
"@aica/components/core-vision" = "v1.1.2" # contains CameraStreamer
"@aica/foss/toolkits/ml" = "v1.0.0-cpu24.04" # prerequisite for YoloExecutor

# other extensions
"@aica/foss/web-video-server" = "v0.1.0" # enables web streaming of video topics 
# launcher syntax: ghcr.io/aica-technology/web-video-server:v0.1.0
"object-detection-utils" = "docker-image://object-detection-utils" # self-built component to feed goal frame extracted from yolo to robot velocity controller

# add hardware collections
#"@aica/collections/intel-realsense-collection" = "v2.0.1" # D4XX and L515 cameras models, stream RGBD
#"@aica/collections/ur-collection" = "v4.3.0"